#ifndef MFTOK_H
#define MFTOK_H

#include <stddef.h>
#include <stdio.h>

#include "../src/common.h"

/*
 * Initialize lexer from a dump generated by `mfgen`. Failure to initialize is
 * guaranteed to not leave any resources allocated.
 *
 * @param lexer: pointer to a preallocated `struct mflexer`
 * @param file: pointer to the FILE of the lexer dump
 *
 * @return `MFSTATUS_SUCCESS` uppon successful completion, `MFSTATUS_ERR_IO` in
 * case of I/O errors or `MFSTATUS_ERR_MEM` in case of allocation errors
 */
int mflexer_init(struct mflexer *lexer, FILE *file);

/*
 * Free any resources held by the given lexer
 *
 * @param lexer: pointer to a `struct mflexer` initialized with `mflexer_init`
 */
void mflexer_destroy(struct mflexer *lexer);

/*
 * Extracts one token from an input stream, according to the given lexer. File
 * position indicator is moved to the end of the identified token. If an invalid
 * token is encountered, the file position indicator is not advanced. Function
 * is not responsible for reporting EOF, however I/O errors are reported.
 *
 * @param lexer: pointer to a `struct mflexer` initialized with `mflexer_init`
 * @param file: pointer to the stream to be tokenized
 *
 * @return the type of the identified token, `MFSTATUS_INVALID` in case of an
 * invalid token or EOF, `MFSTATUS_ERR_IO` in case of I/O errors
 */
int mflexer_tokenize_stream(const struct mflexer *lexer, FILE *file);

/*
 * Extracts one token from an input string, starting from `offset`, according
 * to the given lexer. Value pointed to by `offset` is set to the end of the
 * identified token. If an invalid token is encountered, the offset is not
 * advanced. Function is not responsible for reporting the end of the string.
 *
 * @param lexer: pointer to a `struct mflexer` initialized with `mflexer_init`
 * @param string: string to be tokenized, ending with `\0`
 * @param offset: position relative to the beginning of `string`
 *
 * @return the type of the identified token, `MFSTATUS_INVALID` in case of an
 * invalid token or end of string
 */
int mflexer_tokenize_string(const struct mflexer *lexer, const char *string
	, size_t *offset);

#endif
